### ISSUE TITLE
gatsby-desing-tokens update 

### ISSUE THREAD

**Issue by greglobinski** [gatsby-inc/gatsby-interface#181] opened 2020-01-03 15:04 UTC
After refactoring usage of desing-tokens at Cloud and gatsbyjs.com I came to some conclusions which I would like to discuss here with you.

As the [doc](https://github.com/gatsby-inc/gatsby-interface/blob/master/docs/design-tokens.md) describes we are (at Cloud app and gatsbyjs.com) pretty much in harmony with tokens at `gatsby-desing-tokens`. However there is a space to make usage of our design-tokens even more consistent across all of our sites.

# Tokens

### 1. Consistent 
There are tokens which are imported and re-exported from `gatsby-interface` without any change (besides adding `types`). **Nothing to change!**

### 2. Recalculated
There are tokens which we recalculate to `rem` values. **Nothing to change!**

### 3. Extended
There are tokens which we had to extend to have the Cloud UI unbroken. I believe **it would be valuable to apply following extensions to the package**. 

#### space

```javascript
// gatsby-desing-tokens
[0, 4, 8, 12, 16, 20, 24, 32, 40, 48, 56, 64, 72]
```

```javascript
// gatsby-interface extended options
[0, 2, 4, 8, 12, 16, 20, 24, 32, 40, 48, 56, 64, 72, 84, 96]
```

added values `2, 84, 96`. The change will affect the gatsbyjs.com code  :warning: so we will need to fix that but I think it's worth the effort.

#### transition

```javascript
// gatsby-interface (inline comments point extension)
transition = {
  curve: {
    default: `cubic-bezier(0.4, 0, 0.2, 1)`,
    fastOutLinearIn: `cubic-bezier(0.4, 0, 1, 1)`, // extension
  },
  speed: {
    snail: `1000ms`, // extension
    slow: `500ms`, // overwrite original value `350ms`
    default: `250ms`,
    fast: `100ms`,
    blink: `50ms`, // extension
  },
}
```
`transition.speed` is not only extended, the `slow` value is overwritten to `500ms`, the `gatsby-interface-token` value is `350ms`, so the step between default and slow is pretty small only `100ms`. This extensions will be neutral for the gatsbbyjs.org code and the visual change (longer `slow` transitions) almost unnoticeable, 

### 4. Reformatted
There are tokens which values we reformatted for easier usage. I believe **it would be valuable to apply following re-formating to the package**. 

#### fonts
`gatsby-desing-tokens` exports values of fonts as `arrays` of `string`. To use the values in `css` we have to use `join()` method. The same way the values are re-formatted  at gatsbyjs.org, so why do not change it in the package?

#### radii
```javascript
// gatsby-desing-tokens
[0, 2, 4, 8, 16, 9999, `100%`]
```
```javascript
// gatsby-interface
[
    0: `0px`, 
    1: `2px`, 
    2: `4px`, 
    3: `8px`, 
    4: `16px`, 
    5: `9999px`, 
    6: `100%`
  ]
```
Omitting `px` symbols works pretty well for `css` single values, but every time you want to use the `radii[1]` in css shortcut we have to manually add `px` to the token

```javascript
// that works without explicitly set unit 
borderRadius: props.theme.radii[6],
...  
// but below we have to add unit postfix
border-radius: ${t.radii[2]}px 0 0 ${t.radii[2]}px;
```
That makes usage of tokens inconsistent. Let's fix it. The change will affect the code of gatsbyjs.org!  :warning:

### 5. Incompatible

There are also tokens which values are completely different

#### zIndices
```javascript
// gatsby-desing-tokens
{
  widget: 2,
  navigation: 5,
  banner: 10,
  modal: 10,
  sidebar: 10,
  floatingActionButton: 20,
  skipLink: 100,
}
```
```javascript
// gatsby-interface
{
  background: 0,
  base: 1,
  dropdowns: 10,
  toasts: 100,
  modals: 1000,
  a11yIndicators: 10000,
}
```
As we see it's not easy to find common parts (keys/values) between the two implementation. My suggestion is to unify the values with a completely rewritten structure. We can completely omit the need to looking for perfect key names with `zIndices` tokens like this

```javascript
{
	0: 0,
	1: 1,
	2: 2,
	5: 5,
	10: 10,
	20: 20,
	100: 100,
	1000: 1000
	10000: 10000
}
```  
This will provide all values for gatsbyjs.com, gatsbyjs.org and Cloud app. The change will affect all sites using the current `zIndices`. :warning:

# Consistency

All described updates are the steps to make `gatsby-desing-tokens` a source of our **common design-tokens for all of our sites/apps**. That also means that everything what is not **common** should be removed from the package. 

For example there are `sizes` (https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-design-tokens/src/sizes.js) which are only related to gatsbyjs.org and there is no way that we can or should unify the values across all of our sites. That means that the `sizes` should be removed from the package and defined locally in gatsbyjs.org

Or we can use different approach. We can build `gatsby-desing-tokens` into  a series of separate bundles. 

For example:
- `core` with common tokens
- `org` will contain the extensions for `gatsbyjs.org` or `core` + extensions

This way importing only `core` dist we will not have to worry about overriding values related to different sites.

**Comment by amberleyromo** [comment] 2020-01-03 19:39
# 3. Extended

## **space**

> added values 2, 84, 96. The change will affect the gatsbyjs.com code ⚠️  so we will need to fix that but I think it's worth the effort.

👍 

## **transition**

> transition.speed is not only extended, the slow value is overwritten to 500ms, the gatsby-interface-token value is 350ms, so the step between default and slow is pretty small only 100ms. This extensions will be neutral for the gatsbbyjs.org code and the visual change (longer slow transitions) almost unnoticeable,

Not certain I 💯 understand which way you're advocating for, but seems to me the difference between "default" (`250ms`) and the original "slow" (`350ms`) is so minuscule that it'd be worthwhile to consolidate to be `500ms` across both. (We might be agreeing here, lol)

# 4. Reformatted

## **fonts**

> `gatsby-desing-tokens` exports values of fonts as arrays of `string`. To use the values in `css` we have to use `join()` method. The same way the values are re-formatted at gatsbyjs.org, so why do not change it in the package?

👍 

## **radii**

👍 to fixing it to include postfix from `gatsby-design-tokens`

# 5. Incompatible

## **zIndices**

> My suggestion is to unify the values with a completely rewritten structure.

👍 I like the idea of removing the need to come up with a keyname. Instead of having to look it up to find out, you know exactly what you're getting.

# Consistency

> All described updates are the steps to make gatsby-desing-tokens a source of our common design-tokens for all of our sites/apps. That also means that everything what is not common should be removed from the package.

I lean toward the first approach you describe, where `gatsby-design-tokens` reflects a single common set of tokens and additional needs are accommodated locally in context, as needed.

I think if we go with the second approach we start walking down the road of needing to do this audit again -- where slightly diverging styles are redefined (or duplicated) in the bundle.

**Comment by Elanhant** [comment] 2020-01-03 23:28
This is a great write-up 👍, and I will read it more thoroughly later, but for now I have one comment:
> My suggestion is to unify the values with a completely rewritten structure. We can completely omit the need to looking for perfect key names with zIndices tokens like this

I actually feel that semantic names are better than just numbers since they make it more clear to contributors what value should they use. Perhaps `dropdowns`, `toasts` etc are too implementation-related to be helpful, in which case we could name them base on "priority", e.g.
```javascript
{
  normal: 0,
  elevated: 1,
  hovering: 10,
  message: 100,
  blocking: 1000,
  service: 10000,
}
```
Or, if we do want to use numeric keys instead of strings, we can adopt the approach used for `space` or `fontSize` and just have a scale of ascending z-indices:
```javascript
[0, 1, 10, 100, 1000, 10000]
```
What do you think?

**Comment by greglobinski** [comment] 2020-01-07 14:50
> it'd be worthwhile to consolidate to be 500ms across both

@amberleyromo :+1:

**Comment by greglobinski** [comment] 2020-01-07 14:57
``` 
{
  normal: 0,
  elevated: 1,
  hovering: 10,
  message: 100,
  blocking: 1000,
  service: 10000,
}
```

@Elanhant  I can't think of the proposed key names as 'obvious choices', I already started to ask myself  "why it is 'blocking' or 'service' etc?" Are the key names universal across different sites/apps? I think that they are not so my +1 goes to 

```[0, 1, 10, 100, 1000, 10000]```

**Comment by fk** [comment] 2020-01-09 12:29
And sorry again. C***** s****.

### 3. Extended
#### space

Just adding the obvious: The added `2` does also have an impact on .org.

I took a quick first look at where in .com and `gatsby-interface` we are using this spacing token, and there aren't _that many_ occurences — `gatsby-interface`:

<img width="399" alt="Bildschirmfoto 2020-01-09 um 12 49 53" src="https://user-images.githubusercontent.com/21834/72065470-94468700-32de-11ea-9700-4e818ddd94c3.png">

For .com, I'm unsure if I searched in the right place:

<img width="591" alt="Bildschirmfoto 2020-01-09 um 12 53 15" src="https://user-images.githubusercontent.com/21834/72065673-0f0fa200-32df-11ea-9fda-1dce81224389.png">

I'm wondering if we should take another look and see if we can somehow get past adding this additional step, and get away with just a base 4 scale somehow. (I'm aware that my designs most likely are the cause of this additional step)

#### transition

:+1: to @greglobinski's suggestion. Let's provide default values that actually differ enough, and do whatever bespoke thing we need in the appropriate context and code.

I like [Polaris'](https://shopify.github.io/polaris-tokens/) range of values, and naming:

<img width="389" alt="Bildschirmfoto 2020-01-09 um 13 10 38" src="https://user-images.githubusercontent.com/21834/72066706-8fcf9d80-32e1-11ea-94ef-9213a951fe69.png">

### 4. Reformatted
#### fonts

> The same way the values are re-formatted at gatsbyjs.org, so why do not change it in the package?

True. These started as array of strings because they originated with `typography.js` in mind, which expects an array. When we switched .org to use `theme-ui`, the theme for the latter became the single source of truth, thus https://github.com/gatsbyjs/gatsby/blob/a4e5fb9ebb94f1145cd20279bb8703788c072f54/www/src/utils/typography.js#L6-L8.

I personally like the array as string format just because it's fool-proof (and I am a fool ;-)), but yeah, we won't consume this in any other way then a CSS value any time soon. It'd be easy enough to provide both variants, not sure if it's worth it though — other than avoiding another breaking change, I don't have any arguments, just edgy "maybe sometime in the future" stuff.

#### radii

> That makes usage of tokens inconsistent. Let's fix it.

True. This made me think of the `space` scale again — isn't this true for that, too?

### 5. Incompatible

#### zIndices

First of all, I think the differences we are seeing here would also justify _removing_ this from the tokens package, does that make sense? AFAIK, .com, .org, and Cloud are the main three consumers of the design tokens package. I think removing the zIndex values from the package, and allowing us a bit more time to harden what we have in the context of `gatsby-interface` and the components we provide that correspond with those tokens is a valid way forward.

Second, I totally follow @Elanhant's argument:

>  actually feel that semantic names are better than just numbers since they make it more clear to contributors what value should they use.

… and then again, the raw array has advantages, too. I guess I'll be forever torn in between the two.
That said, @greglobinski's arguments also make sense to me. This stuff is hard! 😰 😅 

### Consistency

> That means that the sizes should be removed from the package and defined locally in gatsbyjs.org

:+1: Very true. I'm voting to remove stuff from `gatsby-design-tokens`, @amberleyromo said it best already. Once we see different consumers of the tokens align on certain things, we can revisit adding default tokens.

**Comment by fk** [comment] 2020-02-07 17:38
PR for an initial v2 of `gatsby-design-tokens` is up at https://github.com/gatsbyjs/gatsby/pull/21240. TL;DR: All but the `space` scale modification is in (respectively "out") — detailed info in the PR description.

**Comment by fk** [comment] 2020-02-10 13:33
Ay, this is missing a youtube link: https://www.youtube.com/watch?v=zhVgbZdMdb0

**Comment by fk** [comment] 2020-03-12 20:56
@greglobinski @Elanhant With https://github.com/gatsby-inc/gatsby-interface/pull/230 in, should we close this, and continue the discussion about `space` and [local tokens](https://github.com/gatsby-inc/gatsby-interface/blob/master/docs/design-tokens.md#local-tokens) in a new issue?

**Closed** 2021-06-02 10:44 UTC
